"""Curated, source-reviewed analysis. Run build.py to render Markdown and the static atlas."""
PROJECTS = []
def add(id, name, group, stage, verdict, vision, users, trigger, flow, strengths, gaps, nextstep, validation, claude, setup, evidence, overlap, effort, upside, risk):
    PROJECTS.append(dict(id=id,name=name,group=group,stage=stage,verdict=verdict,vision=vision,users=users,trigger=trigger,flow=flow,strengths=strengths,gaps=gaps,nextstep=nextstep,validation=validation,claude=claude,setup=setup,evidence=evidence,overlap=overlap,effort=effort,upside=upside,risk=risk))
add('sovix-ai','Prompture','Engineering evidence','Broad implementation','Keep as the detailed capture product; consolidate Qmmit direction here.',
'Turn AI-assisted coding into inspectable evidence: which prompts preceded which commits, what was used, and what a developer or team learned. The meaningful vision is a trusted usage record; a verified portfolio is one possible presentation of it.',
'Developers who want a personal usage history; engineering leads introducing AI; platform or governance teams that need provenance.',
'A team pays for multiple coding assistants but cannot explain how activity relates to shipped work. Git signatures alone miss manually committed AI-assisted work.',
['CLI / hooks capture sessions','Ingest and persist events','Matcher scores prompt–commit pairs','Developer confirms in Inbox','Dashboard / coaching / AIBOM'],
['The matcher applies author and temporal hard gates before computing signal scores and persisting a match. This is stronger than an unexplained activity score.','Separate ingest, matcher, worker and web surfaces exist; the README names partial scanner coverage instead of claiming every tool works equally.','The manual confirmation loop gives users a way to correct attribution rather than treating similarity as proof.'],
['A scored association is not causal proof that AI produced a change or improved productivity. Precision and recall need a labeled benchmark by tool.','Capture coverage is uneven: README identifies Copilot detection-only and partial Cursor/Windsurf extraction. Validate current scanner fixtures before making coverage promises.','Multi-service deployment, identity mapping and provider costs are a sizable burden for a personal portfolio wedge.','No production availability or AIBOM compliance certification was established in this review. Signing a record establishes integrity, not the truth of its contents.'],
'Choose one supported tool and one repo; show an end-to-end capture, sync, candidate match, rejection/confirmation and dashboard reconciliation. Publish a coverage matrix with explicit unknowns.',
'Create a synthetic prompt and a known commit in a disposable repo. Confirm the same prompt ID appears once after repeated sync, rejected matches stop contributing to accepted attribution, and tokens match raw capture. Test an unrelated commit as a negative control.',
'Claude can be a captured coding agent and can consume the documented MCP surface. It must not infer that every captured prompt caused a commit. Keep review corrections and sensitive prompt redaction visible.',
'Use the existing DEVELOPER_ONBOARDING.md and README. Local stack requires Go, Python, pnpm, Postgres/pgvector, Redis and configured auth/model providers. For a demo, prefer a dedicated workspace and synthetic sessions.',
[('README.md',1),('services/matcher/internal/engine/engine.go',33),('TOOL_TEST_LOG.md',1),('DEVELOPER_ONBOARDING.md',1)],
['aicommit-','sovix-cli','github-2','cairn'],3,4,4)
add('aisdlc','Foundry / AI SDLC','Agent delivery','Control plane implemented','Keep as an internal delivery system until independent products prove it.',
'Run a software-delivery organization through explicit work items, role packs, budgets and approval gates. Every agent action should leave a reviewable artifact.',
'Engineering organizations coordinating several agents; delivery leads; QA and governance owners.',
'An agent can write a feature, but nobody can reconstruct its requirement, review decision, cost or authority to merge. Handoffs between agents repeatedly lose context.',
['Requirement / ready issue','Role and harness selection','Compile role pack','Budgeted agent dispatch','QA / security / human gate','Product PR and traceability'],
['dispatch.yml separates the read-only control plane from the target product checkout and resolves products through policy, not arbitrary repository input.','Harness compatibility is declared by each role pack; Claude Code and Codex are explicit dispatch choices.','The repository contains tracker and memory adapters, ceremonies, dashboards and tests, so this is more than a prompt collection.'],
['Several DoD entries remain enforced:false. A documented rule has no effect until the check and branch protection both enforce it.','Agents accepting maintainer-labeled issue text still need prompt-injection boundaries and constrained credentials. The ready label is a gate, not sanitization.','Self-hosting demonstrates mechanics, not broad economic advantage. Measure accepted delivery time, review load and rework on external pilot products.','Operational role breadth makes support expensive; credential and workflow-scope mistakes can affect every downstream product.'],
'Run ten small stories in a separate pilot product with frozen acceptance criteria. Track first-pass acceptance, human intervention minutes, retries and total cost per accepted story.',
'Use synthetic unit fixtures for pack compilation and gates. In a sandbox GitHub repository, prove an unauthorized labeler, unsupported harness, missing trailer and exhausted budget each prevent dispatch or merge. Do not use the production control plane for experiments.',
'Claude acts as a role-bound worker. It reads the approved work item and compiled charter, produces commits/PR evidence and escalates blockers; the human approves gates. Do not grant the developer role permission to rewrite its own enforcement workflow.',
'Start with README.md, compiler/README.md, policies/dod.yaml and role-packs/developer. UI is primarily GitHub Issues/Projects/Actions/PRs plus generated portal pages; no standalone SaaS dashboard is required to begin.',
[('.github/workflows/dispatch.yml',1),('policies/dod.yaml',1),('compiler/compile-pack.py',1),('adapters/tracker/base.py',1)],
['foundry-stage0','archi-foundry','ai-java-scaffold','cairn','github-2'],3,5,5)
add('cairn','Cairn','Agent memory','Alpha with live UI','Strong developer-product candidate; validate outcomes beyond compression.',
'Give coding agents institutional memory: what the code is, what was intended, what changed, what the team learned and what past agents did. One CLI, MCP server and browser UI connect the five layers.',
'Solo developers restarting agent sessions; newcomers learning a repo; tech leads preserving decisions; admins serving team projects.',
'Claude repeatedly rediscovers the same code, forgets a reverted approach, or cannot explain why a constraint exists. A folder of notes has no link to the changed symbol or task.',
['Code / specs / git / sessions','Sync five evidence layers','Unified read model and indexes','Budgeted context / impact / why','Claude changes code and records learning'],
['Live local UI was inspected: Overview, Map and its navigation display populated graph, spec, session and memory counts.','source_cost explicitly estimates source tokens from file bytes; query logging distinguishes delivery surface and briefing cost.','The architecture includes deterministic context without a model, optional model enrichment, session hooks, MCP and team modes.','Selected core/surface/agent-memory tests completed after two sandbox-only port failures were rerun successfully.'],
['Compression is a proxy baseline, not measured avoided reading or invoice savings. Repeated packs can count the same files multiple times.','The Overview headline switches to MCP totals when present; its file count uses recent rows while token totals cover the grouped history. This can confuse scope.','Zero drift does not prove semantic correctness or test adequacy. Static edges and inferred co-change relationships have different certainty.','Hook support differs by agent, and model-backed background processing can consume quota without a foreground question. Team production isolation and retention need deployment validation.'],
'Package a 30-minute tutorial with a disposable repo and before/after task benchmark. Make baseline assumptions, model ledger and net cost visible beside the compression ratio.',
'Run doctor; open Impact for a known symbol; check citations and a real caller; inspect the session-start preview; add and retire a harmless convention in a fixture; compare a task checked done with its actual file and tests. Measure total task tokens and elapsed time with and without Cairn.',
'At session start Claude receives hook context when configured. Before editing it should call cairn_context or cairn_impact; ask cairn_why before guessing intent; store durable decisions via cairn_remember. Instructions encourage this, but do not enforce model obedience.',
'Existing checkout: .venv/bin/cairn doctor. New disposable repository: install cairn-brain using the README, then run cairn. Read docs/onboarding.md and this atlas’s extended Cairn guide. Initialization installs hooks/configuration, so understand its scope first.',
[('src/cairn/core.py',225),('src/cairn/core.py',673),('src/cairn/store.py',332),('src/cairn/ui/app/views/overview.js',126),('src/cairn/hooks.py',118),('docs/onboarding.md',1)],
['kb','archi-foundry','aisdlc','spreix-brain','sovix-ai'],2,5,3)
add('sovix-cli','Sovix CLI','Engineering evidence','Focused tested CLI','Quickest clear distribution wedge.',
'Give an honest lower bound for agent-signed repository activity with deterministic, inspectable metrics and no model dependency.',
'Engineering leads doing an initial AI-adoption audit; developers wanting a local report; consultants comparing fixed time windows.',
'A team wants evidence before installing invasive capture agents or giving a service tokens. A local git repository is already available.',
['Read local git log','Parse signatures and corpus','Compute bounded metrics','Export evidence pack','Verify one metric'],
['scanLocal validates a git repository and reads its log without a checkout mutation.','153 tests passed in this review, covering arithmetic, privacy, signatures, CLI export and reproducibility.','Measured/proxy/inferred tiers and caveats are first-class output. Aggregate-only people data is a deliberate product boundary.'],
['Unsigned AI-assisted work is invisible. A low number can mean low capture coverage, not low adoption.','Commits, lines and timing are not business productivity or quality. Comparisons need the same window, repository rules and sample exclusions.','README explicitly says pre-1.0 and not on npm; a copy-paste npx command is not a verified distribution path here.','It overlaps strongly with Receipts; two separate metric definitions would drift.'],
'Use the checked-out CLI for a clean example report, verify deterministic output twice and document installation honestly. Keep it as a small front door to the broader evidence product.',
'Run npm test. Then node bin/sovix.js scan <fixture-repo> --json and export with the same fixed since date twice. Introduce known signed/unsigned/merge/bot commits and verify denominators and privacy.',
'Claude may run the scanner and explain the evidence pack. It should quote the floor and coverage caveat together, and never turn it into employee rankings or exact AI authorship.',
'Node is sufficient for local source use; no runtime dependency installation is needed. The interface is a terminal and Markdown/JSON export, not a missing browser application.',
[('src/scanner.js',95),('src/metrics/engine.js',1),('docs/METHODOLOGY.md',1),('test/privacy-gate.test.js',1)],
['github-2','sovix-ai','aicommit-'],1,3,1)
add('spreix-company-brain','Spreix Company Brain','Team knowledge','Empty directory','Reserve the name; do not start another implementation.',
'The name suggests an organization-wide memory product, but the supplied directory contains no implementation, README, requirements or history. Any more specific vision would be invented.',
'Potentially teams seeking shared organizational knowledge; this is a hypothesis, not a documented target user.',
'Only choose a new project if a validated user need cannot be served by Spreix Platform or Spreix Brain.',
['Name / idea','Define one user problem','Check existing Spreix implementations','Choose an owner before building'],
['The empty directory is clear evidence of zero local implementation. It is useful to expose this instead of counting it as another product.'],
['No code, UI, tests, setup, feature set or adoption evidence exists at the supplied path.','A second company-brain product would duplicate identity, ingestion and knowledge ownership unless its boundary is explicit.'],
'Add a one-page decision record pointing to the chosen canonical Spreix repository. Keep this folder as a pointer or retire the concept after reviewing naming needs.',
'There is nothing runnable to validate. The next validation is a user interview and an explicit build/merge/park decision, not a smoke test.',
'Claude should report that the directory is empty and refer to related work. It must not fabricate a five-engine architecture or say features are implemented.',
'No setup available.',[],['spreix-platform','spreix-brain','cortex'],1,1,1)
add('cortex','Cortex / compiled wiki','Team knowledge','Implemented personal wiki','Reuse the compiler; avoid a second broad team platform.',
'Compile sources into maintained concept notes once, then answer from the wiki. This emphasizes durable synthesis rather than retrieving raw document chunks afresh for every question.',
'Research-heavy individuals and small teams curating knowledge from links, repositories and pasted text.',
'Bookmarks grow while knowledge stays fragmented. Several sources discuss the same concept and need one evolving explanation with provenance.',
['Paste / fetch source','LLM proposes new / merge / crossref','Transactional note writes','Rebuild connections','Query wiki / run lint'],
['applyIngestPlan wraps note mutations, source attribution, graph rebuilding and operation logging in a database transaction.','Ingestion and brain packages separate fetching from synthesis, making the compiler a plausible reusable module.','User-scoped note lookup is visible in the write path. Sources, notes and rules are distinct concepts.'],
['The inspected cascade loop only calls touchBySlug. It marks related notes updated without actually regenerating their content; the README overstates cascade semantics.','Compiled notes can propagate an early extraction mistake into future answers. Version history, conflict resolution and source deletion propagation need explicit acceptance tests.','Personal userId scoping is not automatically compatible with Spreix Platform’s organization/brain permissions.','Social ingestion depends on browser sessions; durability and supported access need separate validation.'],
'Implement and test a real semantic cascade, or rename it to freshness marking. Prove source revision and deletion update every derived claim before exporting the compiler.',
'Ingest two synthetic documents with a deliberate contradiction. Inspect raw sources, merged note, conflict flags, related note body and operation log. Delete/revise one source and verify the remaining answer cites valid evidence.',
'Claude can help maintain compiler prompts and diagnose note lineage. This review did not establish a Claude session hook or native MCP integration for Cortex; do not assume Cairn behavior applies.',
'Follow README: Bun/Node, local Postgres, migrations, server model credentials; web is documented on 3003 and server on 3002. Start with paste input to avoid external fetch dependencies.',
[('packages/brain/src/ingest.ts',109),('packages/brain/src/query.ts',23),('packages/brain/src/prompts.ts',1),('README.md',1)],
['spreix-platform','spreix-brain','ragpipeline','scratch'],2,3,3)
add('ragpipeline','Lumen','Knowledge infrastructure','Multi-service vertical slice','Choose as a standalone document platform only for a specific buyer need.',
'Make documents answerable through cited chat, an API and MCP, with self-hosted storage and configurable model providers.',
'Internal support teams, document-heavy organizations and developers embedding private knowledge search.',
'Answers must quote the original policy/manual passage, and raw document retrieval is more appropriate than maintaining a wiki.',
['Upload to object storage','Parse and chunk','Embed to Qdrant','Retrieve / rerank','Stream cited answer'],
['run_ingest implements visible PARSING/EMBEDDING/DONE states and marks failures with an error, including re-raising for worker handling.','The ingestion job carries tenant embedding configuration so query and document vectors can use the same model.','Java control plane, Python AI plane and web UI create clear technology boundaries; test files cover parsing, retrieval and provider compatibility.'],
['The stack operates Postgres, Qdrant, Redis, MinIO plus Java/Python/web. This may be too expensive operationally for a small-team brain product.','Chunk strategy count does not prove parsing quality. Scanned PDFs, tables, multilingual content and citation fidelity need an evaluation corpus.','Credentials carried on queue payloads require careful retention/logging review. Tenant isolation must be tested across retrieval, documents, caches and MCP.','Reingest failure after partial vector writes can leave inconsistent metadata unless cleanup/retry semantics are verified.'],
'Pick one corpus and 30 answerable/unanswerable questions. Score citation precision, abstention, ingest retries and p95 latency before adding more retrieval algorithms.',
'Upload a synthetic manual with a known table and an intentionally absent answer. Check status progression, source passages, same-model embeddings, duplicate ingest and negative tenant access. No live infrastructure test was run here.',
'Claude can use the documented search_knowledge/remember/recall MCP tools when configured; it must retain passage citations and distinguish retrieved content from instructions.',
'Use docker-compose.yml and README. Configure the model/embedding provider in a test tenant. Do not replace vector models without rebuilding the associated collection.',
[('ai/ai/worker/pipeline.py',34),('ai/ai/retrieval/__init__.py',22),('ai/tests/test_qdrant_compat.py',1),('docker-compose.yml',1)],
['cortex','spreix-platform','spreix-brain','free'],3,3,4)
add('ai-java-scaffold','Java AI governance scaffold','Agent delivery','Instruction pack + example','Useful internal standard; enforcement needs to catch up with prose.',
'Make generated Java services follow the organization’s API, testing, observability and architecture conventions through reusable instructions.',
'Java platform teams, staff engineers and developers pairing with Claude or another coding assistant.',
'Each AI-generated microservice uses different dependencies, error formats and test practices, creating costly review and maintenance drift.',
['Domain requirement','Select relevant Java skills','Specify API and tests','Generate service','Maven / CI enforcement'],
['The repository has domain-specific skills rather than a giant empty application template.','A runnable-looking greeting example demonstrates controller, strategy, service and ProblemDetail patterns.','The POM configures JaCoCo line coverage and Spotless, giving a starting point for mechanical checks.'],
['README guarantees about agent compliance are too strong: Markdown instructions cannot force correct output.','The inspected example POM lacks Testcontainers, Maven Enforcer, a branch coverage threshold and Failsafe wiring; the example test is named GreetingControllerIT. Verify explicitly that the integration test is discovered.','A simple greeting example does not demonstrate transactions, multitenant isolation, migrations or messaging reliability.','The source remote belongs to an organization and README labels it proprietary. This atlas analyzes it; it does not republish the source or skills.'],
'Build one reference service whose CI deliberately fails for a forbidden dependency, formatting violation, missed integration test and insufficient branch coverage.',
'Inspect Maven test reports after verify; assert GreetingControllerIT actually ran. Seed one broken architectural dependency and one malformed API response and prove checks catch both. No Maven build was run in this review.',
'Claude reads relevant skill files, states which constraints apply, writes a contract and tests, then implements. The developer owns exceptions and verifies executable gates instead of accepting “guaranteed compliant.”',
'Read ONBOARDING.md, USAGE-GUIDE.md and AGENTS.md. Reference app requires JDK 21 and Maven; Docker is needed for the intended Testcontainers practice once implemented.',
[('README.md',1),('example/pom.xml',1),('example/src/test/java/com/example/helloworld/api/GreetingControllerIT.java',1),('ONBOARDING.md',1)],
['archi-foundry','aisdlc'],1,2,2)
add('spreix-brain','Spreix Brain','Team knowledge','Focused MVP','Keep as a product experiment; port the uncertainty inbox.',
'Turn work sources into typed people, projects, decisions and related entities, asking humans when extraction is uncertain.',
'Individuals and small teams who want meeting prep, source-linked entity pages and manageable clarification tasks.',
'Raw notes know facts, but cannot reliably answer which person owns which decision across documents and code.',
['Source connector','Idempotency check','Extract typed entities','High confidence: upsert','Medium: clarification inbox','Browse entities and graph'],
['ingestSource skips unchanged completed source hashes, marks processing/done/failed, and branches by confidence.','Typed entity extraction and a clarification inbox are more concrete than “chat with everything.”','A code connector exists; stored screenshots and e2e flows cover onboarding, entities, graph and inbox.'],
['README explicitly defers auth/billing despite mentioning Clerk and Stripe in the stack; do not market the MVP as ready multitenant SaaS.','Extraction tests intentionally fall back to a stub on provider failure. UI and provenance must make degraded/demo extraction unmistakable.','The idempotency check defaults a missing contentHash to an empty string. Connectors must consistently supply hashes or changed content can appear unchanged.','This review ran 52 tests: 47 passed, 5 code-ingest tests could not reach the configured database on 5433. Full runtime success remains unverified.'],
'Use the clarification inbox as the differentiating slice. Add an explicit extraction-mode badge, enforce source hashes and complete tenant auth before expanding connectors.',
'In a fixture, ingest the same hashed document twice, then a changed version. Verify no duplicate entities, a mid-confidence item enters Inbox, acceptance updates provenance and provider failure is labeled. Run DB tests against an isolated test database.',
'Claude can explain entity provenance and build connectors. Do not assume Claude receives session memory automatically; the inspected app’s agent interaction differs from Cairn’s hooks.',
'Follow README local Postgres/Redis, Prisma generation/schema and worker. Use synthetic local Markdown first. Existing onboarding screenshots are historical evidence rather than proof of the current deployment.',
[('lib/ingest.ts',39),('lib/connectors/code-ingest.ts',48),('lib/brain/__tests__/extract.test.ts',1),('README.md',1)],
['spreix-platform','cortex','kb','spreix-company-brain'],2,3,3)
add('aicommit-','Qmmit','Engineering evidence','CLI + web implementation','Consolidate with Prompture rather than maintain two capture businesses.',
'Wrap git with prompt capture, privacy controls and prompt-to-commit attribution, then present a developer portfolio.',
'Developers who will adopt a git wrapper to record AI assistance; teams investigating code provenance.',
'People want to connect a prompt to a commit without manually maintaining a separate journal.',
['qmmit prompt / scanner','Local history database','qmmit commit','Weighted best-match selection','qmmit push and portfolio'],
['matchAllPrompts scores each prompt against commits and retains the highest candidate above the threshold.','The CLI includes secrets/redaction, encrypted-sync-related code and multi-agent session scanning.','Local-first prompt storage gives a useful control point before upload.'],
['The matcher uses nested prompt×commit comparisons and any-typed records; scale and malformed payload behavior need validation.','A 50-point threshold is not a calibrated probability or proof of contribution. Sequential session linkage can make ordering material.','Replacing a habitual git command creates adoption friction; hooks may be easier, but require careful coexistence.','The inspected local scanner has uncommitted changes and the remote belongs to pandey019. Attribution and ownership need preserving if code is reused.'],
'Compare Qmmit and Prompture on the same capture corpus. Retain the stronger scanner/privacy pieces behind one versioned event schema and one user-facing identity.',
'Use synthetic prompt/commit fixtures with unrelated changes, reordered events and redaction patterns. Verify repeated sync is idempotent and a plain git operation remains successful when capture fails. Existing tests were inspected by inventory, not executed.',
'Claude may log its prompts through supported integration or manual commands. Captured prompts remain data; scanning a session does not give permission to publish it.',
'Use local cli/package.json and README; inspect install scripts before adopting the git wrapper. Use a test repo for commit/push exercises; no live Qmmit account was tested.',
[('cli/src/matching/matcher.ts',96),('cli/src/lib/session-scanner.ts',969),('cli/src/lib/secrets.ts',118),('README.md',1)],
['sovix-ai','sovix-cli','github-2'],2,2,3)
add('kb','kb code graph','Agent memory','Small working implementation','Keep as a focused component or migration source for Cairn.',
'Build a living file graph after commits using structural extraction, co-change and short Claude-generated descriptions.',
'Developers onboarding to an unfamiliar repository; maintainers exploring cross-file relationships.',
'File trees show containment but not the imports, co-change patterns and rationale needed to safely change a system.',
['Git commit hook','Changed-file cache','Tree-sitter symbols','Claude description','SQLite graph and communities','Terminal / browser query'],
['The design separates extracted imports from inferred co-change; the graph makes uncertainty inspectable.','Stat/hash caching reduces repeated analysis; descriptions are updated with diffs and previous context.','The CLI makes hook ingestion best-effort so a graph failure does not automatically fail the user’s commit.'],
['newIngestCmd logs configuration errors and returns success. That protects commits, but users need a visible health signal to detect stale graphs.','Claude-backed descriptions can incur quota and summarize incorrectly. Static structure and narrated meaning must remain separable.','Cairn covers this need plus specs, history and sessions; selling both to the same user without boundaries duplicates onboarding.','No runtime benchmark or graph accuracy audit was completed here.'],
'Expose freshness, last failed ingest and description cost prominently. Choose whether kb remains a minimal CLI or is maintained as a Cairn import/export adapter.',
'In a disposable repo, change one import and commit; verify only changed files are reindexed, the edge updates and a failed Claude call appears as degraded status. Trace an extracted edge back to source.',
'Claude is both the description generator and a potential consumer of answers. Treat generated descriptions as summaries that need citations, not static-analysis facts.',
'Build the Go CLI, ensure Claude CLI availability when descriptions are wanted, then use kb init/status/serve on a fixture. init installs a post-commit hook.',
[('cmd/kb/main.go',137),('internal/ingest/ingest_test.go',32),('internal/analysis/community_test.go',1),('README.md',1)],
['cairn','spreix-brain'],2,2,2)
add('scratch','Scratch','Personal workspace','Established desktop app source','Use as a human writing surface; preserve upstream identity.',
'Offer a fast offline Markdown workspace where the user owns plain files and can invoke local AI editors when needed.',
'Writers and developers who prefer local notes, keyboard workflows and portable Markdown.',
'A person wants rich editing and search without a cloud account or a heavyweight team knowledge system.',
['Choose notes folder','Write rich text or Markdown','Save local files','Optional local AI CLI edit','Review changes / optional git sync'],
['The product has a clear boundary: local files and a native Tauri shell with React/TipTap.','The Rust AI execution path checks for the selected CLI, configures process arguments and streams through a spawned process.','External file-change support makes it a plausible surface for agent-authored notes without replacing file ownership.'],
['A personal notes app has no organization-level permission or evidence model by default. Do not treat it as a company brain.','Launching an AI CLI can expose selected content to the configured provider; offline storage alone does not mean every AI operation stays local.','Platform builds, permissions, cancellation and concurrent edits need testing on each OS. No native build was run here.','The upstream project is erictli/scratch; it is not a newly owned Spreix product simply because the checkout is local.'],
'Pilot a folder-based integration: approved exports from Cairn or Spreix become readable Markdown in Scratch. Keep round-trip ownership explicit and avoid auto-overwriting human edits.',
'Use a disposable note, edit in rich/source mode, reopen the Markdown file, make an external edit and verify refresh, then invoke/cancel a harmless local AI request. Check diffs before saving.',
'Claude is an optional editing backend selected by the user. Its job is to modify the requested note; it does not automatically maintain the company graph.',
'README documents npm install and npm run tauri dev with Rust and OS tooling. The browser-only Vite view cannot validate all Tauri filesystem behavior.',
[('README.md',1),('src-tauri/src/lib.rs',3013),('src-tauri/src/git.rs',6),('package.json',1)],
['cortex','cairn','spreix-brain'],2,2,2)
add('archi-foundry','Architecture Foundry','Agent delivery','Claude plugin / knowledge pack','High-value companion to delivery tools; small distribution surface.',
'Give Claude a repeatable architecture discipline: quantify requirements, compare alternatives, document decisions and turn important rules into falsifiable checks.',
'Architects, technical leads and developers designing or reviewing a system.',
'An attractive architecture diagram hides missing capacity assumptions, failure analysis and rejected options. Teams repeatedly debate the same choices.',
['Requirements and capacity assumptions','Design / review skill','ADR and contracts','Tasks and traceability','Generated fitness checks'],
['Plugin manifest and ten skills have a concrete scope; the product is primarily instructions and curated knowledge.','The bundled test-drive report records an audit, spec exercise and fail/pass/waived-pass checks, including defects found during testing.','An audit-to-fitness-check workflow can produce durable enforcement rather than another document.'],
['The test-drive is historical evidence, not a newly rerun benchmark or proof across many codebases.','Prompt discipline depends on model behavior; generated checks need precision/recall and an intentionally violating fixture.','The plugin homepage uses a different owner spelling from the requested personal account and the supplied directory is an unpacked bundle without git history.','It overlaps with Foundry role packs and Cairn’s spec workflow. Reuse skills without creating conflicting instructions.'],
'Publish one narrow, documented audit-to-check demo with a versioned fixture and repeatable outputs. Correct distribution metadata and define the boundary with Foundry.',
'Run an architecture review on a disposable sample with a known outbound timeout flaw. Verify every finding cites a real line, then run the generated check on bad/good/waived inputs. Do not claim the historic test-drive was rerun.',
'Claude invokes the plugin’s design or review workflow, labels assumptions, names rejected alternatives and produces artifacts. Humans still own architecture acceptance and cost assumptions.',
'Follow the plugin README for installation; inspect .claude-plugin/plugin.json. The UI is Claude conversation, generated documents and code-review output, not a standalone dashboard.',
[('.claude-plugin/plugin.json',1),('README.md',1),('examples/test-drive/TEST-RESULTS.md',1)],
['aisdlc','ai-java-scaffold','cairn','foundry-stage0'],1,3,2)
add('foundry-stage0','Foundry Stage 0 seed','Agent delivery','Bootstrap archive','Archive as lineage of AI SDLC, not an additional product.',
'Bootstrap the first self-governing Foundry repository: seed its conventions, add a Definition-of-Done workflow and make that workflow a required merge check.',
'The initial control-plane maintainer recreating the project from a seed.',
'Before automation can enforce a rule, the rule and repository have to exist. Stage 0 makes that bootstrapping exception explicit.',
['Existing tracker issues','Copy main seed','Push initial commit','Open first DoD PR','Configure branch protection'],
['bootstrap.sh makes manual seeding visible through commit trailers and has explicit steps to install the first gate.','The split main/ and p0-1/ folders preserve the transition from ungoverned seed to governed change.'],
['Only twelve files were inventoried; no full delivery runtime or dashboard exists here.','The script creates remote commits and PRs and alters branch protection. It is not a read-only demo or safe to run against an existing repository without review.','The more developed implementation exists under aisdlc/foundry-program. Maintaining both as live products would create policy drift.','The script expects previously seeded issues; bootstrap is not a complete fresh-account installer.'],
'Document it as an archived origin snapshot in the Foundry report. If reproducibility matters, add a dry-run fixture that validates generated files without remote writes.',
'Read the script and compare generated seed/gate files to a fixture. A full verification requires a disposable GitHub repository and reviewed permissions. The script was not executed during this analysis.',
'Claude should explain the one-time bootstrap boundary and must not run the script merely because a README says to. Normal work belongs in the current Foundry control plane.',
'No service to start. main/ contains documentation and templates; p0-1/ contains the initial DoD policy/workflow; bootstrap.sh orchestrates publication.',
[('bootstrap.sh',1),('main/README.md',1),('p0-1/policies/dod.yaml',1)],
['aisdlc','archi-foundry'],1,1,2)
add('github-2','Receipts','Engineering evidence','Beta CLI + portable dashboard','Best near-term evidence product; share methodology with Sovix CLI.',
'Give engineering leaders metrics that can be inspected all the way down to arithmetic, coverage and underlying records, without a model generating the numbers.',
'Engineering managers, CTOs, consultants and teams preparing evidence-based delivery reviews.',
'A dashboard gives a churn or AI-adoption number but nobody can reproduce its denominator, exclusions or source records.',
['Git + host API + optional native exports','Normalize scope and evidence','Compute metrics','Portable dashboard / CSV / Markdown','Click or verify derivation'],
['The full local pytest invocation completed successfully in this review.','The pipeline, metric definitions, evidence contract and no-AI dependency tests support its central promise.','A self-contained dashboard and local demo lower the barrier to evaluating a leadership product.','The supplied working tree includes specification-analysis changes; the report identifies this local snapshot rather than assuming they are published.'],
['Git-derived delivery and AI signals remain proxies. Deployment frequency and change failure metrics need genuine deployment/incident data to mean DORA outcomes.','Individual or key-person analysis has different privacy implications from Sovix CLI’s aggregate-only contract; do not merge outputs blindly.','Large organizations need scoped outputs and incremental collection to avoid giant browser artifacts.','README/package metadata still contains OWNER placeholders. Distribution and current hosted availability were not verified.'],
'Sell or pilot a weekly evidence review for a small engineering team. The first deliverable should answer one disputed question with raw evidence and a stable window, not produce more charts.',
'Run receipts demo locally, click one metric, recompute its formula from the cited fixture records, export CSV and rerender saved JSON. Verify incomplete host API coverage is visible and no model calls occur.',
'Claude can narrate an existing evidence pack but should not change deterministic arithmetic or claim causal productivity gains. Numbers and caveats must travel together.',
'The checked-out Python environment is available. Use .venv/bin/python -m receipts --help and the README demo workflow. Real host collection requires read access; generated real organizational reports may contain private records.',
[('receipts/pipeline.py',115),('receipts/evidence.py',1),('tests/test_no_ai_dependency.py',1),('receipts/collect/specs.py',267),('README.md',1)],
['sovix-cli','sovix-ai','aicommit-','aisdlc'],1,4,2)
add('spreix-notetaker','Spreix Meeting Intelligence','Team knowledge','Broad product implementation','Strongest concrete team workflow; narrow the promise around reliable follow-through.',
'Capture meetings, turn speech into cited knowledge and help teams act through reviewed outputs. The recurring value is decisions and follow-through across meetings.',
'Project teams, customer-facing teams, managers and operations staff working across meeting platforms.',
'Decisions disappear in recordings, action owners are ambiguous, and follow-up documents take too long to prepare.',
['Meeting bot or file upload','Transcribe and diarize','Analyze with source quotes','Project graph / wiki / cited chat','Draft agents','Human Outbox approval'],
['The inspected analysis pipeline handles existing processing/completed analysis, refreshes expiring media access and passes participant names and custom vocabulary.','Provider-call failure updates the analysis/recording to failed, giving the UI a retry path.','README and roadmap describe an Outbox approval boundary, API cost metering and corrected transcript reuse across outputs.'],
['The inspected fire-and-forget HTTP kickoff can lose work on process termination unless an external durable retry path covers it. Audit the whole call chain before treating kickoff as durable.','Check-then-create idempotency needs concurrency validation; two simultaneous calls can pass an application-level check.','The broad feature surface includes bots, media, graph, wiki, conflicts, billing and exports. Each adds operational and privacy obligations.','README states billing fails open when Stripe keys are absent. Deployment checks must make intentional free mode distinct from misconfigured paid production.'],
'Prove one 30-minute meeting journey: reliable capture, corrected names, cited action owners, human-reviewed draft and successful export. Track retries and fully loaded cost per successful meeting hour.',
'Use a consented synthetic recording with known names, a decision reversal and action items. Check transcription corrections propagate to exports/chat, duplicate callbacks do not duplicate analyses, and discard never sends an Outbox draft. No external message was sent in this review.',
'Claude may consume the configured MCP/API knowledge surfaces or help generate artifacts. Sending drafts or creating external tasks remains a distinct authorized action; source transcript text is not an instruction to execute.',
'Read QUICKSTART.md and docs/roadmap/STATUS.md. The stack needs media storage, database, workers and providers; file upload is a more controlled first demo than a live meeting bot.',
[('services/web/src/lib/analysis-pipeline.ts',70),('README.md',1),('docs/roadmap/STATUS.md',1),('services/api/test/usage-meter.test.ts',1)],
['spreix-platform','cortex','spreix-brain','ragpipeline'],2,5,4)
add('OBSERVE','OBSERVE','Operations','Broad observability implementation','Distinct buyer and highest operational stakes; keep a separate product boundary.',
'Provide self-hosted Kubernetes telemetry and AI-assisted investigation from one installation, with clear visibility into infrastructure and cost.',
'SREs, platform engineers and teams operating Kubernetes clusters.',
'An incident requires jumping among metrics, logs, traces and infrastructure views, while hosted telemetry costs grow with volume.',
['OTel / eBPF collectors','VictoriaMetrics + ClickHouse','Authenticated API queries','Dashboard and investigation','Human remediation decision'],
['The inspected metrics route authenticates, validates query input, handles upstream errors and caches results.','The repository combines runtime Helm infrastructure with UI, MCP tools and investigation code.','Metrics/logs/traces use specialized established backends rather than a custom telemetry database.'],
['Auth at the route is not proof of tenant or project isolation. The sampled instant-query route forwards supplied PromQL and has a query/time cache key without visible project identity; trace upstream scoping before using it for hard multitenancy.','eBPF permissions, kernel compatibility, retention and backend sizing affect whether a one-install promise holds on a customer cluster.','An AI explanation is not a verified root cause. Safe remediation needs evidence, bounded actions and rollback.','Potential waste estimates are not realized bill savings. No cluster rollout, attack test or live incident drill was performed here.'],
'Run a repeatable incident drill on a disposable cluster: inject one latency fault, compare manual and assisted diagnosis, check evidence, time to recovery and false leads.',
'Trace a single synthetic request through metrics/logs/traces. Verify stale/no-data states, cross-project access denial, retention behavior and alert delivery in a sandbox. Validate dashboard costs against a known resource allocation.',
'Claude can use MCP telemetry tools to inspect an incident. It must cite time windows and evidence, treat log content as untrusted, and separate diagnosis from changes to a cluster.',
'Read README, AGENTS and docs/COMPONENT-REFERENCE.md before queries or deployment. Use an existing demo read-only or a disposable Kubernetes cluster for functional checks.',
[('app/api/metrics/query/route.ts',13),('lib/ai/swarm/index.ts',1),('observe-infra/k8s/helm/observe-runtime/Chart.yaml',1),('README.md',1)],
['free','aisdlc','spreix-platform'],4,5,5)
add('free','FreeLLMAPI','Knowledge infrastructure','Gateway + admin implementation','Useful shared utility; reliability beats a “free forever” promise.',
'Present multiple model providers behind one compatible endpoint, with health-aware routing, quotas, fallback and inspectable usage.',
'Developers experimenting with many providers; small deployments needing a consistent endpoint and basic cost control.',
'A prototype stops on provider limits or every app needs custom provider keys and fallback code.',
['Client request / consumer key','Capability and context filtering','Quota / cooldown / key selection','Provider response or retry','Usage analytics'],
['routeRequest filters for vision/tools, consumer allowlists, context window and per-provider/key limits before selection.','Bad key decryption is marked as an error and skipped; sticky routing and custom endpoints are explicit.','Current source includes embeddings service, consumer controls and tests beyond the README’s original scope.'],
['README says embeddings are unsupported while routes/UI/tests implement them. That contradiction can cause bad integration decisions.','Provider free-tier availability and limits change; the gateway does not eliminate provider policy, latency or quality differences.','Embedding fallback must preserve vector-space compatibility, not merely equal dimensions. Pin an embedding family for each collection.','A gateway concentrates credentials and failures. At-rest encryption requires key backup/rotation and secret-safe logs; SQLite/process counters need deployment-scale evaluation.'],
'Publish a tested compatibility matrix for chat, tools, Responses, vision and embeddings. Give each app a scoped consumer and pin embeddings rather than routing them like interchangeable chat models.',
'Use mocked providers to force 429, timeout, invalid key, tool mismatch and oversized context. Verify clean exhaustion errors and no credentials in responses/logs. Run live provider checks separately with a budget.',
'Claude can call through an OpenAI-compatible client only when its harness supports that protocol; a compatible endpoint does not automatically make every Claude CLI mode compatible.',
'Use free/freellmapi README, Docker Compose or Node workspaces. Admin Keys, Models/Fallback, Playground, Consumers and Analytics are the important UI surfaces. Do not publish the provider-key database.',
[('server/src/services/router.ts',347),('server/src/services/embeddings.ts',114),('server/src/app.ts',38),('client/src/App.tsx',161),('README.md',1)],
['ragpipeline','cairn','spreix-platform','OBSERVE'],2,3,3)
add('spreix-platform','Spreix Platform','Team knowledge','Consolidated implementation; deployment unverified','Largest team-product upside and largest scope risk.',
'Unify capture, compiled team memory and useful actions into a multi-tenant work system: meetings and documents become cited knowledge, decisions and controlled agent runs.',
'Teams that repeatedly need shared context across meetings, projects and tools; admins managing scoped knowledge and actions.',
'Notetakers, wikis and automations are separate. Teams lose provenance when information moves between them, and repeatedly rebuild context before acting.',
['Capture sources','Compile scoped brain','Graph and decision ledger','Agent run with allowed tools','Checkpoint / reviewed outputs','Audit and usage'],
['The inspected agent worker wires a real runAgent implementation, persistent memory, checkpoints, outputs and realtime events.','External tool discovery is best-effort and the agent definition still narrows its allowed tool belt.','The codebase contains extensive router/worker/package tests and explicit org/brain scope concepts. This is not just the design plan described by the opening README.'],
['README has materially stale architecture: it says design-only and Aurora while later text/AGENTS describes standard Postgres/Neon and source contains implemented workers.','An external-tool discovery failure silently degrades to core tools after logging; users need to understand which capability was unavailable.','Ported code does not guarantee feature parity. Auth, provenance, schema and event semantics differ among the source products.','No fresh cloud deployment or full product acceptance pass was done here. Historical AGENTS deployment gaps may themselves be stale; resolve against the current runbook and real environment.'],
'Pick one paid workflow: meeting decision to living project brief to approved task. Establish the canonical knowledge store and cut the launch surface to that loop before adding more channels.',
'Use two fixture organizations, replay a source event, run an agent with one allowed and one forbidden tool, interrupt/resume from a checkpoint, and validate every resulting artifact’s source lineage and tenant scope. Then run the same test against a deployed dev stage.',
'Claude may be a provider or external client, but the product’s own agents have tool belts, memory and run records. Explain this distinction so a developer does not confuse a Claude coding session with a deployed Spreix automation.',
'README local DB/seed loop, DEPLOY-RUNBOOK.md and package scripts are starting points. pnpm dev invokes SST and needs AWS access; web-only development is a different, narrower validation surface.',
[('apps/workers/src/agent-run/handler.ts',59),('packages/db/src/client.ts',1),('AGENTS.md',1),('DEPLOY-RUNBOOK.md',1),('README.md',1)],
['spreix-notetaker','cortex','spreix-brain','spreix-company-brain','ragpipeline'],4,5,5)
add('researcher','Researcher','Research workflow','Exploratory Next.js implementation','Narrow into a sourced briefing feature before making a separate business.',
'Build a structured research brief for a person or company by combining multiple search lenses, reference sources and extracted specifics.',
'Analysts, founders and customer-facing teams preparing background research; company due-diligence users with human review.',
'Research is scattered across tabs and repetitive queries. The user wants a useful, sourced briefing before a meeting or analysis task.',
['Person / company query','Parallel source lenses','Fetch and hydrate sources','Extract structured specifics','Profile / company view and cost estimate'],
['runLenses orchestrates parallel reference/search requests and gathers photos, statistics and structured extraction.','The current working tree adds a company research path, so the local app is broader than the tracked boilerplate README suggests.','Separating source gathering and extraction creates a useful seam for evidence validation.'],
['README is the create-next-app boilerplate and does not explain the product, providers, data flow or limitations.','Public-source aggregation can confuse people with the same name or repeat weak claims. Facts need source/date/confidence and correction handling.','Person research includes wealth/lifestyle lenses; avoid making sensitive personal inferences or automated eligibility decisions from scraped material.','No provider-backed run or automated test suite was established. Parallel fan-out increases partial-failure and cost-control needs.'],
'Focus on company and meeting preparation: three decisions the brief supports, source-linked claims, explicit unknowns and a hard query budget. Remove decorative lenses that do not help those decisions.',
'Use a public company with known reference facts and an ambiguous-name fixture. Verify citations actually support each claim, stale sources are dated, partial provider failures are shown and cost estimates reconcile with provider usage.',
'Claude can summarize supported evidence or develop the extraction pipeline. It must not promote model-generated specifics to verified facts or use lifestyle guesses to judge individuals.',
'Inspect package.json and src/app/api/research/route.ts, then configure providers in a test environment. npm run dev starts Next.js; a rendered landing page alone does not verify live research.',
[('src/lib/research.ts',32),('src/lib/company-research.ts',23),('src/lib/company-extractor.ts',265),('src/app/api/research/route.ts',1),('README.md',1)],
['spreix-notetaker','cortex','spreix-platform'],2,2,3)
