"""Source-grounded UI/CLI walkthroughs; intended exercises unless marked live."""
JOURNEYS = {
'sovix-ai': [('Connect and capture','Use the existing developer onboarding to connect a disposable repository and supported coding tool.','A session and repository identity appear; unsupported capture is explicit.'),('Review attribution','Open the prompt/commit review Inbox; inspect one candidate and reject an unrelated pair.','Accepted and rejected associations remain distinguishable.'),('Read the result','Open the project dashboard and follow the evidence behind one metric.','The same event IDs and fixed time window reconcile with the capture record.')],
'aisdlc':[('Prepare work','Use GitHub Issues and the role-pack workflow to express a small story and acceptance checks.','The issue has the required fields and authorized readiness gate.'),('Dispatch','Inspect the Actions run for the selected role, harness, target checkout and budget.','Artifacts identify the correct product and approved scope.'),('Review','Open the resulting PR and its DoD checks.','A missing required gate blocks progress; documented-but-disabled checks are not counted as enforced.')],
'cairn':[('Orient','Choose the project; open Overview, then Map and Impact.','Known source files and callers can be verified; sync age is visible.'),('Recover intent','Open Specs, Timeline and Memory around a concrete task.','The cited requirement or prior decision actually supports the advice.'),('Resume','Inspect Sessions and the next-session preview.','A new configured agent session receives relevant context; token accounting is scoped.')],
'sovix-cli':[('Inspect help','Run node bin/sovix.js --help in the checked-out project.','The source CLI works without assuming an npm release.'),('Scan a fixture','Run node bin/sovix.js scan <fixture-repo> --json with the documented window options.','JSON contains explicit scope and caveats.'),('Explain one number','Export the evidence pack and recompute one signed-activity metric.','Unsigned work remains unknown and personal data follows the aggregate-only contract.')],
'spreix-company-brain':[('Inspect the placeholder','There is no UI or CLI at the supplied location.','The absence of implementation is recorded.'),('Choose the product home','Compare Spreix Platform and Spreix Brain reports.','A decision record names the owner instead of beginning another duplicate app.')],
'cortex':[('Add a source','Start with paste ingestion in the web app using synthetic text.','The source appears and compilation has a visible outcome.'),('Inspect the wiki','Open the concept note and its source/connection references.','Merged content retains provenance; related-note bodies are checked separately from timestamps.'),('Ask and revise','Ask a question, then revise the original source and rerun ingestion.','The answer changes only when evidence warrants it; stale/conflicting claims are visible.')],
'ragpipeline':[('Upload','Create a test workspace and upload a synthetic manual.','The document moves through processing states or exposes a useful error.'),('Ask','Use cited chat to ask for a table value and then a deliberately absent fact.','The table value points to the right passage; the absent answer is not invented.'),('Use the API','Repeat the question through the documented API/MCP contract.','Tenant scope, source IDs and citation meaning match the UI.')],
'ai-java-scaffold':[('Load the rules','Read the onboarding and select applicable Java skills in the coding assistant.','Claude states the API, error-format and test constraints before generating code.'),('Build the example','Use JDK 21 and Maven on a copy of the example.','Inspect actual test reports; a successful build is insufficient if the IT test never ran.'),('Review enforcement','Introduce one deliberate rule violation in a fixture.','An executable check fails; prose-only rules are identified as review responsibilities.')],
'spreix-brain':[('Connect a fixture','Use onboarding to ingest a small local Markdown source.','The source status and extraction mode are visible.'),('Resolve ambiguity','Open the clarification Inbox and review a mid-confidence entity.','Accepting the suggestion updates the correct entity with source provenance.'),('Browse knowledge','Open Entities and Graph, then inspect the source of a relationship.','The entity reflects a real extraction; stub mode must not look like a provider-backed result.')],
'aicommit-':[('Capture locally','Use the documented qmmit prompt/scanner path in a disposable git repository.','A prompt is stored locally with redaction behavior checked.'),('Make a known change','Use the documented commit flow and inspect the best-match candidate.','The candidate can be compared to an intentionally unrelated commit.'),('Review before upload','Inspect what qmmit push will synchronize before using a test account.','Sensitive prompts remain excluded; repeat sync does not duplicate records.')],
'kb':[('Initialize a fixture','Build the Go CLI and run kb init in a disposable repository.','The installed hook and local graph location are understood.'),('Inspect the graph','Run kb status and kb serve; follow an extracted file edge.','The edge corresponds to a real import and freshness is known.'),('Change one file','Commit an import change and inspect the resulting graph.','Only relevant data changes; failed description generation is visible without blocking the commit.')],
'scratch':[('Choose a folder','Open the native app with a disposable Markdown directory.','Notes are real local files and can be opened outside the app.'),('Edit both ways','Switch between the rich editor and Markdown; edit externally and return.','Formatting survives round trips and external edits are recognized.'),('Try AI carefully','Select a configured AI CLI and request a small note edit.','Streaming, cancellation and file diffs behave correctly before you retain the change.')],
'archi-foundry':[('Install the bundle','Inspect the plugin manifest and follow its README installation instructions.','Claude can discover the architecture skills; no web dashboard is expected.'),('Review a known flaw','Ask for an architecture audit of a small fixture with a missing timeout.','Findings cite real code and distinguish assumptions from established constraints.'),('Turn a rule into a check','Generate a fitness check and run bad, good and waived fixtures.','The check detects the intended violation without a blanket false positive.')],
'foundry-stage0':[('Read the seed','Open main/ and p0-1/ side by side.','The initial conventions and first enforcement gate are distinct.'),('Inspect bootstrap','Read bootstrap.sh without running it against existing projects.','Remote commits, PR creation, issue prerequisites and branch protection changes are understood.'),('Reproduce only in a sandbox','Use a disposable GitHub repository if a historical reconstruction is needed.','The first gated PR is reproducible; current delivery work remains in AI SDLC.')],
'github-2':[('Generate demo evidence','Use the checked-out receipts demo workflow.','A portable dashboard is generated from known fixtures without a model call.'),('Inspect a metric','Open a metric and examine arithmetic, exclusions and records.','A reviewer can recompute it and see coverage limitations.'),('Export and reproduce','Export CSV/Markdown and rerender saved JSON.','The same fixed dataset produces the same result; proxies are labeled.')],
'spreix-notetaker':[('Bring a recording','Use a synthetic file upload first, then test an authorized meeting bot separately.','Recording and analysis status move forward or expose a recoverable failure.'),('Check the transcript','Open the meeting detail and compare speakers, timestamps and quoted claims.','A corrected transcript is used by later summaries and actions.'),('Review the output','Inspect project knowledge and agent-generated drafts in the Outbox.','A reviewer can trace an action to a quote and discard it without sending anything.')],
'OBSERVE':[('Connect a test environment','Follow the installation docs for a disposable cluster and inspect telemetry health.','A deliberate test signal arrives with the intended environment labels.'),('Investigate','Select a fixed time range and follow metrics/logs/traces for a synthetic incident.','Queries resolve to the right service, version and scope.'),('Check isolation','Use separate test users/projects to inspect the same route boundaries.','Unauthorized telemetry is denied, including query/cache paths; a visible dashboard alone is insufficient.')],
'free':[('Add a provider','Use a test provider key in the gateway dashboard.','The stored key is protected and provider health/caps are visible.'),('Call the consumer API','Make a small compatible chat request from a test client.','The chosen model/provider and usage reconcile with the response.'),('Exercise the contract','Test streaming, tools, embeddings and exhaustion separately where supported.','Unsupported capabilities fail clearly; vector dimension/model stays consistent across ingest and query.')],
'spreix-platform':[('Establish workspace','Use the implemented auth/workspace/brain flow in a configured test deployment.','Organization and brain identity remain consistent across pages and worker inputs.'),('Ingest and query','Add a synthetic source and inspect its knowledge/provenance.','Queries return only authorized sources with visible processing state.'),('Run an agent','Start a bounded agent run and inspect checkpoints, output and tool availability.','Missing integrations are labeled; external actions follow the configured approval boundary.')],
'researcher':[('Enter a subject','Use a public company with independently known facts.','The UI starts a research run with a clear subject identity.'),('Inspect the brief','Follow claims to their underlying URLs and publication dates.','Ambiguous identity, missing evidence and partial provider failures remain visible.'),('Reconcile cost','Compare displayed estimates with the actual provider request/usage records.','Parallel fan-out respects the query budget; the result is a sourced draft for human review.')]
}
